name: Test mpx workflow

on: [pull_request, workflow_dispatch]

run-name: MPX

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      
      - name: Download reads
        run: |
          mkdir reads
          cd reads
          wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR206/024/SRR20689724/SRR20689724_1.fastq.gz
          wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR206/024/SRR20689724/SRR20689724_2.fastq.gz
          cd ../

      - name: Run Cecret
        run: |
          nextflow run . -profile docker,mpx -c .github/workflows/github_actions.config --maxcpus 2 --medcpus 2

          ls cecret*
            
          head cecret*/cecret_results.txt

      - name: Clean
        run: rm -rf work .nextflow*
